### LAFDS Session 3 Homework

### Calculating the inverse of a 2x2 matrix without using numpy
> Code a function to calculate the determinant of 2x2 matrix<br>
Code a function that interchange the diagonal elements of a 2x2 matrix and inverse the sign of the off diagonal elements<br>
Code a function to compute the inverse of 2x2 matrix based on the two previous functions if it exists<br>


In [1]:
M = [[5,4],[6,7]]

In [2]:
def det_of_2x2(M):
     return M[0][0] * M[1][1] - M[0][1] * M[1][0] 

In [3]:
det_of_2x2(M)

11

In [4]:
def change_and_inverse_of_2x2(M):
    return [[M[1][1], -1*M[0][1]], [-1*M[1][0], M[0][0]]]

In [5]:
change_and_inverse_of_2x2(M)

[[7, -4], [-6, 5]]

In [6]:
M

[[5, 4], [6, 7]]

In [7]:
def inverse_of_2x2(M):
    det = det_of_2x2(M)
    adj = change_and_inverse_of_2x2(M)
    from copy import deepcopy
    M_inverse = deepcopy(M)
    for row in range(len(adj)):
        for number in range(len(adj[0])):
            M_inverse[row][number] = adj[row][number]/det
            
    return M_inverse

In [8]:
M_inverse = inverse_of_2x2(M)
M_inverse

[[0.6363636363636364, -0.36363636363636365],
 [-0.5454545454545454, 0.45454545454545453]]

In [9]:
M

[[5, 4], [6, 7]]

In [10]:
import numpy as np

In [11]:
m = np.array(M)
np.linalg.inv(m)

array([[ 0.63636364, -0.36363636],
       [-0.54545455,  0.45454545]])

### Coding a Python code to inverse a 3x3 matrix in order to solve a linear system (no numpy.linalg.inv allowed) with 3 constraints and 3 variables:
> Coding a function that checks if a 3x3 matrix is invertible<br>
Coding a function that generates the transpose of a 3x3 matrix<br>
Coding a function that generates the matrix of minors of a 3x3 matrix<br>
Coding a function that generates the matrix of cofactors of a 3x3 matrix<br>
Coding a function that generates the inverse of a 3x3 matrix if it exists<br>


In [12]:
def Minors_matrix(M):
    from copy import deepcopy
    M_minor =  deepcopy(M)
    for row in range(len(M)):
        for column in range(len(M[0])):
#             print(del_row_column(M,row,column))
            M_minor[row][column] = det_of_2x2(del_row_column(M,row,column))
    return M_minor

In [13]:
def det_3x3(m):
    minors = Minors_matrix(m)
    return minors[0][0]*m[0][0]-minors[0][1]*m[0][1]+minors[0][2]*m[0][2]

In [14]:
def is_invertible(M):
    try:
        if det_3x3(M) != 0:
            return True
        else:
            return False
    except:
        pass

In [15]:
is_invertible(m)

In [16]:
m = [[5,4,9],[6,7,19],[11,13,6]]

In [17]:
def transpose_matrix(Matrix):
    from copy import deepcopy
    M_T =  deepcopy(Matrix)
#     M_T =  [[0]*len(m)]*len(m[0])
    for i in range(len(M_T)):
        
        for j in range(len(M_T[0])):       
#             print(i,j)
#             print(M_T[i][j])
#             print(Matrix[j][i])
             M_T[i][j] = Matrix[j][i]
    
    return M_T

In [18]:
MT = transpose_matrix(m)
MT

[[5, 6, 11], [4, 7, 13], [9, 19, 6]]

In [19]:
np.transpose(m)

array([[ 5,  6, 11],
       [ 4,  7, 13],
       [ 9, 19,  6]])

In [20]:
m = [[5,4,9],[6,7,19],[11,13,6]]

In [21]:
def del_row_column(M,row,column):
    from copy import deepcopy
    Msmall =  deepcopy(M)
    Msmall.pop(row)
    for row in range(len(Msmall)):
        Msmall[row].pop(column)
        
    return Msmall

In [22]:
m = [[5,4,9],[6,7,19],[11,13,6]]

In [23]:
Minors_matrix(m)

[[-205, -173, 1], [-93, -69, 21], [13, 41, 11]]

In [24]:
def Cofactor(M):
    from copy import deepcopy
    M_Cofactor = deepcopy(M)
    for row in range(len(M)):
        for column in range(len(M[0])):
            M_Cofactor[row][column] = ((-1)**(row+column+1+1))*M[row][column]
            
    return M_Cofactor

In [25]:
Cofactor(m)

[[5, -4, 9], [-6, 7, -19], [11, -13, 6]]

In [26]:
def inverse_3x3(M):
    if is_invertible(M):
        minors = Minors_matrix(M)

        det = det_3x3(M)

        cof = Cofactor(minors)

        adj = transpose_matrix(cof)

        from copy import deepcopy
        M_inverse = deepcopy(M)
        for row in range(len(adj)):
            for number in range(len(adj[0])):
                M_inverse[row][number] = adj[row][number]/det

        return M_inverse
    else:
        print("Can't be inverted")
    

In [27]:
np.linalg.inv(m)

array([[ 0.63271605, -0.28703704, -0.04012346],
       [-0.53395062,  0.21296296,  0.12654321],
       [-0.00308642,  0.06481481, -0.03395062]])

In [28]:
inverse_3x3(m)

[[0.6327160493827161, -0.28703703703703703, -0.040123456790123455],
 [-0.5339506172839507, 0.21296296296296297, 0.12654320987654322],
 [-0.0030864197530864196, 0.06481481481481481, -0.033950617283950615]]